server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_media?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

#mybatis:
  #mapper-locations: com.znlccy.media.core.mapping
  #type-aliases-package: com.znlccy.media.core.model
